### ISSUE TITLE
cURL error 77: error setting certificate verify locations

### ISSUE THREAD

**Issue by martinlowinski** [WP-API/client-cli#30]
Hi,

when running `php wp-cli.phar --require=client.php api oauth1 connect https://example.com --key=key --secret=secret` (obfuscated), I get the following error:

```
Error: cURL error 77: error setting certificate verify locations:
  CAfile: phar:///var/www/html/client-cli/wp-cli.phar/vendor/rmccue/requests/library/Requests/Transport/cacert.pem
  CApath: none
```

Any ideas what the problem might be?

Thanks.

**Comment by rmccue** [comment]
This is some sort of issue with the interplay between wp-cli and cURL, so it's something you should probably file on the wp-cli repo. :)
